### ISSUE TITLE
For datasets

### ISSUE THREAD

**Issue by DrJZhou** [yanaiela/amnesic_probing#1]
Hi, the work is very interesting. Could you please send the dataset to me? My email is jzhou@ica.stc.sh.cn. Thanks!~

**Comment by yanaiela** [comment]
I replied to you in private, but for other people I'll post here as well:

Here is the link to the data: https://nlp.biu.ac.il/~lazary/amnesic_probing/
It also includes the encoded representations, labels, etc.
The data is included and already tokenized: `tokens.pickle`

Re ontonotes, unfortunately this data is licensed, so I cannot share it, but I added all of the data we used with the UD treebank. We did include the processing code for Ontonotes.

Notice that in that folder, there are two files, corresponding to both setups of 'non-masked' and 'masked' versions.
There are also the encoded representations of all layers, where 'last_vec.npy' corresponds to the very last layer of BERT (right before the embedding multiplication).

Feel free to reopen this in case of any questions
